# Generated by Django 2.1.7 on 2019-03-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_anime_name', models.CharField(blank=True, max_length=300, null=True)),
                ('schedule_anime_image', models.CharField(blank=True, max_length=300, null=True)),
                ('schedule_anime_day', models.CharField(blank=True, max_length=50, null=True)),
                ('schedule_anime_date', models.CharField(blank=True, max_length=20, null=True)),
                ('schedule_anime_episode', models.CharField(blank=True, max_length=30, null=True)),
                ('schedule_anime_time', models.CharField(blank=True, max_length=50, null=True)),
                ('schedule_anime_month', models.CharField(blank=True, max_length=100, null=True)),
                ('schedule_anime_year', models.CharField(blank=True, max_length=100, null=True)),
                ('schedule_anime_week_number', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'schedule',
            },
        ),
    ]
