# Generated by Django 2.1.7 on 2019-03-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_schedule_schedule_anime_fanrelated'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='anime_info_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
