# Generated by Django 2.1.7 on 2019-02-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='type',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
