# Generated by Django 2.1.7 on 2019-02-26 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_anime_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='type',
        ),
    ]
