# Generated by Django 2.1.7 on 2019-02-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_anime_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
