# Generated by Django 2.1.7 on 2019-02-26 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190226_2359'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Anime',
        ),
    ]
