# Generated by Django 2.1.7 on 2019-03-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_popularanime'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularanime',
            name='anime_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
