# Generated by Django 2.1.7 on 2019-02-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.CharField(blank=True, max_length=200, null=True)),
                ('tags', models.CharField(blank=True, max_length=600, null=True)),
                ('studios', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.CharField(blank=True, max_length=1000, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('durination', models.CharField(blank=True, max_length=15, null=True)),
                ('scores', models.CharField(blank=True, max_length=20, null=True)),
                ('aired', models.CharField(blank=True, max_length=30, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('gener', models.CharField(blank=True, max_length=200, null=True)),
                ('quality', models.CharField(blank=True, max_length=10, null=True)),
                ('synonyms', models.CharField(blank=True, max_length=300, null=True)),
                ('premired', models.CharField(blank=True, max_length=15, null=True)),
                ('status', models.CharField(blank=True, max_length=15, null=True)),
                ('types', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'info',
            },
        ),
    ]
